### ISSUE TITLE
Implementation highlighting right side text view

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#109]
This entails loading all the parallels that the source and target texts have in common and highlighting all the segments on the right that have a parallel to the text in the left column.

**Comment by sebastian-nehrdich** [comment]
I will do a rough implementation of this in a separate branch soon because I want to demonstrate it in the paper. I think technically speaking it should be possible to recycle the code we use to build the view on the left side and just add a hook to allow only those parallels that have the reference with the text on left hand side.

**Comment by sebastian-nehrdich** [comment]
@ayya-vimala I have been working on this for a while but I got stuck with an issue regarding lit-html.
Maybe you could have a look at it?
In this code:
https://github.com/ayya-vimala/pali-networks/blob/102-load-new-jsons/src/views/options/text-view.js
After one clicks on a middle column parallel, I am rendering the html for the right hand side text in the same manner as for the left hand side text and then I am storing this into context.parallelText and after that call updateFilter() to re-render the display. When rendering the right hand side text, you can see in the console that both objects, left hand side as well as right hand side look identical (save for the content, which is of course a different text). For some reason that I don't get, the text on the left get's rendering fine but right hand side only returns a series of stringified objects but no html is rendered. Do you have an idea why? I guess my understanding of lit-html is just too limitied to grasp this.

**Comment by ayya-vimala** [comment]
In the right panel it needs html string and not objects. So just don't push objects but kit the html strings together.
I'm not entirely sure why but this is what the vaadin-element seems to want.

**Comment by sebastian-nehrdich** [comment]
Yes I realized this, but it's not that pretty I think! Because I would like
to use the same code for highlighting on the left and right side and not
end up with two functions doing the same thing. I really wonder *why* no
objects are accepted at that position. Strangely enough, if I exchange the
variables for parallelText and suttaItems in the template (line 69 and 74),
the root text gets rendered well on the right side, while only [object
Object] appears on the left hand side. The console.log of both Objects
looks identical to me....
Maybe it's a strange bug in lit-html, after all...

**Comment by ayya-vimala** [comment]
What I do is to have the same function with a "frame" id in the call. Frame 1 = render as html object, frame 2 = render as string. But it's a bit hacky I admit and not very nice.

**Comment by sebastian-nehrdich** [comment]
Yes if I can't find a true solution to this I will try a workaround like
that. Also I would like to pass our clickFunction to the highlighted area
as an onclick-event, that's also a bit tricky when just using strings...
But maybe it works to add a listener somewhere later to the DOM.

**Comment by ayya-vimala** [comment]
I suggest you use your new branch to play around with such things and find new solutions, etc. and above all to show Orna. (And deploy all that to the server of course).
Then after the database is fully implemented, we can use the useful bits of that branch. That way you have all the space you need for trying things out, showing and finetuning without having to constantly wait for us to do things or us running into each other.

**Comment by sebastian-nehrdich** [comment]
no problem with this!
Be aware that I am going to remove the current JSON files very soon from
the server so the current master branch is not going to be able to handle
them anymore. I suggest to merge at least once to make sure that the main
branch can work with the new files, or do you have a suggestion how to do
this?

**Comment by ayya-vimala** [comment]
The new jsons will be loaded into the database, parsed into collections and then from there queries will be run which will go into the frontend.

In the mean time, your branch can run separately on the buddhist-db.de server as the main branch and you can maintain that and improve that.
As far as I'm concerned you can remove the old jsons completely as soon as you have your branch running with the new jsons loaded directly into the frontend.

I just want to make sure that we can start our database-integration with the master branch that is there now. We can branch off from there. This will make it much easier for me to see what is going on because I now know how things are loaded and where and which bits to look out for.

**Comment by sebastian-nehrdich** [comment]
OK no problem with doing it this way. If you work directly with the API
then this really doesn't matter, right.

**Comment by ayya-vimala** [comment]
Exactly. And all the improvements you make like the right-side highlighting and anything else Orna would like, can then be implemented after that.

**Comment by sebastian-nehrdich** [comment]
Just for the record, in order to avoid future frustrations: I could fix the problem by moving one level of div from the top-level template to the rendered template that is returned by buildTextViewRight.
This behaviour doesn't really make sense to me, so I assume it might be a bug to lit-html. Anyway, works now...

**Comment by ayya-vimala** [comment]
Possibly, but there might be other reasons why the div was there in the first place (styling or so). Will have a look at it at some point.

**Comment by sebastian-nehrdich** [comment]
Just to make clear: I didn't delete the div, I just moved it into the template that is returned by buildTextViewRight.

**Comment by sebastian-nehrdich** [comment]
it's done now, pushed it to: https://github.com/ayya-vimala/pali-networks/tree/102-load-new-jsons/src
Since the code requires the new json-files, I didn't yet push it to the server. Possibly I gonna exchange everything in one go tomorrow...

**Comment by ayya-vimala** [comment]
Okay ... I will see it once the new jsons are there and its on the server.

**Comment by sebastian-nehrdich** [comment]
Finally, I managed to push it to the server. The url has changed, it it budhist-db.de/ now.
There basic functionality works. But there are some smaller things that need debugging. 
Currently, some files are missing on the server. I can't fix it atm because my internet connection totally died yesterday and I now use my simcard for online access.
The rendering on the right side is basically just a mirror of what happens on the left side. So when one clicks a quote on the right side, in the middle column the parallel of the left text appears. It's a bit funny behaviour, but it also kind of makes sense.  
I noticed that *sometimes*, the quotes recorded for the text on the left side and the quotes on the right side don't match. This points at a bug in my parallel-generation code at some point. In theory, this shouldn't happen. This is why sometimes the text on the right side does not seem to scroll.
Also I had to remove the 'loading...'-bar on the right side because it would break the HTML rendering later onwards. But it would be really nice to have it back, without any feedback about the loading it feels somehow odd.  
I also added a viewport-depending rendering strategy for the text on the left side. It works and I guess that combining this with the API is rather straight-forward.  
Generally speaking, on the text-view code I don't see too many obstacles with the API. 

@ayya-vimala I think next I want to try to merge your recent changes on the descriptions etc. into my branch so everything is up to date.

**Comment by ayya-vimala** [comment]
I had a look at the site. Good work.
I think it needs a few minor changes in CSS. For some reason the middle column parallels have lost their markup (they are no longer in capitals) and the Length and Co-occurances are not as they should be. But those are minor things. (I'm not sure what I think about the green color text either :-))

Not sure why the loading-bar would breat the HTML rendering. 

Also, the combo-box dropdown looks a bit strange so best look at that too. Right now it starts with 4 the same items. I've not checked what causes that yet, just writing down what I noticed.

I just have a question on what exactly is being rendered on the right. Are the highlighted parts the offset values for the parallels where the left text is the root_segment and right text is the parallel_segment? At least that would make sense to me as you said that this is not necessarily the same the other way around.

The test I did with the info buttons and menu are in that separate branch but I would not merge that because the menu is not working and it is basically just a test. I can spend a little time today just creating another branch that just does the info buttons and merge that and then you can merge that into yours too.
