### ISSUE TITLE
paper-slider text input field is to small

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#126]
@ayya-vimala We have a problem with the text-input field being too small at the moment. Especially on the length filter, the last digit is cut off. That's misleading to the users. I already tried for half an hour or so to change the CSS but no good, seems I have two left hands when it comes to CSS. Maybe you have an idea?

**Comment by ayya-vimala** [comment]
I cannot get the mixin to work on this. I don't know why. There are two ways around it: 
1. copy the polymer wc to local folder and use it from there and make all the changes you want (otherwise it just gets overwritten by every npm install).
2. Use the pin option instead of editable.

I've used that option now.

**Comment by ayya-vimala** [comment]
You were very quick pushing that! But there was a little error in the length filter that I corrected so if you are merging this into your branch, be aware of the min-value of the length filter.

**Comment by sebastian-nehrdich** [comment]
ok, thanks for this!
