### ISSUE TITLE
Filter on collection option

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#17]

**Comment by sebastian-nehrdich** [comment]
For the Paris presentation, it would be great if we can do a very simple filtering by at least the two categories Kangyur and Tengyur. If you are too busy Ayya Vimala then I can also look into this.

In the long run it would be perfect if we would first scan the quotations and minimize the filter options to those that are actually present in the quotations (so the user can only choose between categories that are actually quoted and nothing shows up that is irrelevant). Also it would be nice to let the user choose between filter on corpus-level (like abhidharma, NM, DN, and so on), subcorpus and finally file-level (if the user just wants to compare two files for example). This is probably quite some work and not very urgent at the moment.

**Comment by ayya-vimala** [comment]
Right now the filtering filters whatever you put in it:
If you say TD, it will filter all Tengyur. If you say TD4000, it will give you just the results for that one. So it is more flexible that way rather than limiting it just the collection. If you say TD4, you will get everything in the 4000 range, etc.
It is more difficult to do it with all the collections in a dropdown because with the Tengyur/Kanyur files the filenames are not consistent wit h the collection so you need to load an additional list of files in collections, etc. It can probably be done but speed is becoming a big issue here. Maybe at some point looking into MongoDB or ArangoDB would be better.

**Comment by sebastian-nehrdich** [comment]
I didn't notice it is already functioning, sorry for my inattention! I That is actually already very very powerful function now and I like it very much as it is. I will discuss with mission control how they feel about it. I think it could be a bit tricky for users who do not know the data layout/filenames etc. very well. 
I think in order to get a menu structure 'on the cheap' I could expand the filenames in the data generation. For example instead of just TD4064.TXT.r I could do something like T01TD4064.TXT.r for Tengyur category 1 and the same for Kangyur.  Same of course for Pali and Sanskrit, so we agree on a set of codes for the naming. Then we just have to keep a short list of category<>name mapping (e.g. 'expand T01 to 'Prajñāparāmitā' etc). Also I will drop the .TXT.r of the filenames/segment names because that is just generating unnecessary overhead.

**Comment by ayya-vimala** [comment]
What we can do is to put a tooltip on every filter to explain it's workings.
But it might indeed be good to do something like T01, etc in front of the filenames in the segment numbers. So where it says: T01TD4064.TXT.r_342. That should be fairly easy to implement in the data from your end.
For Pali that is not necessary because pali collections match their acronyms.
But I suggest to leave the implementation of this in the frontend until after Paris.

**Comment by sebastian-nehrdich** [comment]
Yes I agree! Maybe for Paris, we can just have a dropdown that will filter for capitel "K" or capital "T" in the files which will give a cheap division into Tengyur and Kangyur and later we can add a more elaborate structure. Having the filter by manual input is also nice, maybe we can have both co-existing. But this is all low priority, if we don't get to it for paris that is OK.

**Comment by ayya-vimala** [comment]
I can have a dropdown with the collections now the T01, etc are in front of it. Will move it back to BackLog.

**Comment by sebastian-nehrdich** [comment]
Having a dropdown for the main categories would already be quite sufficient I think. Also no need to disable entries from the dropdown-menu if they are not in the file - I think if somebody will choose a category and no result will show up, that also says something!
But I think we should keep the search-function as well, so the more advanced user might use it instead/as well.
