### ISSUE TITLE
Adding lenth filter

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#29]
" For example, 'length' would be a nice parameter in addition to 'similarity'. I will add a length-variable to the csv-files so you can easily grab that data."

Comment Vimala: not sure what is meant by this and what "length" is but anything added to the csv files would also need a re-generation of the json files and frontend code.

**Comment by sebastian-nehrdich** [comment]
I think we can close this. 'Length' was an idea by our teamleader for the Tibetan but I have some reservations for that. The idea was to pull together longer quotes that go over multiple segments into one so we get a length-value that can be very different for each quotation. 
I don't totally agree with this practice. I think it makes sense to pull things together within one segment so the same segment doesn't have the same quote twice. But if we start to pull quotes of multiple segments into one, then I really get a knot in my head as to how to display this nicely (especially when there are overlapping shorter and longer quotes). Currently we have the problem that if a quote runs for more than a segment, the user might not immediately see it (he/she has to scroll down to the next segment and see if there is also a quotation). I think this is not a very big issue because the user can open the quoted file in the right column anyway and will then see immediately what is going on. 
Or do you have any idea/suggestion about this? If not, then I think we close this for the time being and see how things develop once the site is running, maybe there will be some feedback of the users as well.

**Comment by ayya-vimala** [comment]
I see. Yes, I agree that would be complicated. I did not know what this meant that is why I put a Refinement label on it. But I'm happy to close it.
