### ISSUE TITLE
Smooth scrolling between texts

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#31]
'smooth scrolling' between texts that share many many parallels (like translations and different versions of the same sūtra) by just moving the mouse-cursor over the text.

**Comment by sebastian-nehrdich** [comment]
As we discussed on skype (19th of June), I have already implemented this in JQUERY. For Paris, if I have some time left after we have the files online, I might be able to add some parameter handling to the JQ so that we can call the smooth-scrolling thing externally by adding someting like ?filename=TD4064.TXT.r to the url. I wonder if we can embed this into an iframe and share the CSS with the main site? That would be a cheap solution to have this feature for the time being integrated as a separate entity in our site. In the long run of course it would be nice to integrate this into our column-view, but that's a bigger issue. 
My impression is that people who want to browse Sanskrit<>Tibetan translations  are unlikely to also want to see the parallels/quotations for each language at the same time, so maybe it is OK for the time being to have this detached from our main viewing option.

**Comment by ayya-vimala** [comment]
iframe is always a quick solution for these things, so yes, that can be done. But I put the Refinement label on because I am not entirely sure what the "smooth scrolling" means. But if you implement it in the Tokyo-code then I can have a look.

Let's discuss it next time.

**Comment by sebastian-nehrdich** [comment]
I think this can be closed because the suggested solution is deprecated. Will open a related and more up to date issue on this today.
