### ISSUE TITLE
Update sankey visualizatin to read Tibetan collections

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#36]
get the display working for Tengyur<>Kangyur, Kangyur<>Kangyur, and Tengyur<>Tengyur-data (at the moment we only of Kangyur<>Tengyur)

**Comment by sebastian-nehrdich** [comment]
(just to make clear: the visualization-style is called sankey and provided by various libraries)

**Comment by sebastian-nehrdich** [comment]
I have uploaded a first version of the visualization. It is now based on google-charts and doesn't require jquery. Currently Kangyur<>Tengyur and Tengyur<>Kangyur work. I will figure out the next days how to add the remaining data (especially Sanskrit). Emacs was in a bad mood today and broke the formatting of the HTML/JS a couple of times, I am therefore sorry for the terrible indents in the sourcecode!
Please feel free to change and modify as much as you like - this is just a quick draft. 
We can do tooltips with this visualization, so I plan to add the full names of the texts as tooltips in the same way as you did it in the menus!

**Comment by ayya-vimala** [comment]
Wow, that's great! So you are using a whole new interface?
Where exactly did you upload it to exactly? Then I can import it into the frontend. Maybe now you've done it completely different, it might be possible to import that into lit-element straight away.

**Comment by ayya-vimala** [comment]
Just had a look at google charts webcomponent and that is so easy to enter into lit element:
https://www.webcomponents.org/element/@google-web-components/google-chart/elements/google-chart
Maybe after the Paris presentation we can have a look or you can fiddle around with it if you like. I am doing a retreat this weekend so I'm a bit busy until Monday. The main thing I still want to do for the presentation is the highlighting.

BTW Where will the presentation be held?

**Comment by sebastian-nehrdich** [comment]
https://github.com/ayya-vimala/pali-networks/tree/master/visualization
Yes I used a different library, this is google-charts. I have not much
knowledge regarding javascript but looks to me like it should be compatible
with lit-elements. At least there is a polymer-package of google-charts so
I can imagine it might be straightforward. Bu on the other hand, no
pressure with this,

**Comment by ayya-vimala** [comment]
Do you have it running somewhere on the buddhist-db site already?

**Comment by sebastian-nehrdich** [comment]
Not yet, but I am uploading it now and will drop the link here.
Maybe, for tomorrow, could you fiddle that visualization which I created
into our current page (just iframe would be enough)? I am a bit hesitant to
do anything that would require editing your code, and I want to skype with
Orna tomorrow to show her the page!
I have already noticed that my visualization looks kind of different than
Kiyonoris. The characteristic of the data is different. I have already some
ideas why this could be the case, but I have to discuss this with Orna.
This is entering the field of philosophy, I guess... ;) ;)
I think we are now very good and there is nothing much on my
Paris-checklist that is missing. I am now fixing the bilingual files and
re-uploading them, after that I will have an early night of sleep today. :)
And probably I will also do a kind of retreat for the weekend... At least
retreat from the computer. ;)
Ah one more think: Two Sanskrit files have changed: T07vakobhau.json turned
into T07vakobhau-1.json and T07vakobhau-2.json. Same is true
for  T07yabhkvyu.tsv which turned into T07yabhkvyu-1.tsv
and T07yabhkvyu-2.tsv. This is just to make the matching with the Tibetan
more straight-forward.

**Comment by ayya-vimala** [comment]
The iframe is the quick and dirty way of doing it quickly. I can fiddle with that right now. That way, if Orna wants the old version it is also easy to change back.
Later on it would be better to rework it into a webcomponent but I had a look at your code and that should be fairly straightforward too.

**Comment by sebastian-nehrdich** [comment]
http://localhost:8000/visualization/display_tibetan.html

**Comment by ayya-vimala** [comment]
Oops ... I have to run ... will do it later. Good work!

**Comment by sebastian-nehrdich** [comment]
No hurry with this! :)

**Comment by ayya-vimala** [comment]
Done that. Looks good.
![Screenshot from 2019-07-04 18-52-51](https://user-images.githubusercontent.com/49606945/60680776-fedcbd00-9e8c-11e9-8ab5-aefef1e4dee5.png)
Personally I would like to do a little bit with the css of that ...

Please note that I moved the folder inside the src folder.
Also, I left your code alone and made two copies of it that autoload the page with automatic settings so I can use my own buttons on the site.
So it's a bit of a hack but it works fine for now and for the presentation.

**Comment by sebastian-nehrdich** [comment]
Thank you, looks great! No problem with the hacky solution! And feel free
to change whatever you want to change.

**Comment by ayya-vimala** [comment]
This is very nice. The only thing I don't like is that when you choose Kangyur <> Tengyur K03 and K05 have the same color.
Also, I'm getting masses of stuff in the console so maybe take the console.log out somewhere.

**Comment by ayya-vimala** [comment]
There is also something about the links. When I click on one it tries to find a file in the wrong location.
For insttance, when I click on K10, it tries to find:

> http://buddhist-db.de/vimala/visualization/sankey/k_t/K10.json 404 (Not Found)

Some on the other side when I click on T02 I get:

> http://buddhist-db.de/vimala/visualization/sankey/k_t/K10/T02.json 404 (Not Found)

**Comment by ayya-vimala** [comment]
I can mess around with the css a bit if you like but don't want to run into what you are doing. Basically I would add more color options, make the text dark grey (so it contrasts with all colors) and with a slightly smaller font size.
Also the postion of the hover text could be a bit more to the middle.

**Comment by sebastian-nehrdich** [comment]
Yes no problem but I created a new version that solves some of the issues
so better wait until I uploaded that! Might do that in about one hour.

**Comment by ayya-vimala** [comment]
And I thought you said something about a retreat from the computer this weekend ... ??? :smiley:

**Comment by sebastian-nehrdich** [comment]
Yes... :D 
I uploaded the new version now on github, it is also online here:
http://buddhist-db.de/visualization/test_google.html
I completed the missing versions (all accesible via the buttons) and changed a bit on the color scheme. 
Regarding CSS: Please change whatever you want to change! I would indeed like to change the placing of the tooltips for the graph, in the best case it should be very close to the cursor/the connected items so that one can see the tooltip also in the case of very distant items. It doesn't really work that well at the moment when there are many texts on either side of the sankey. 
One more thing I would like to change (but I might do that just after Paris) is to move the links from the select-event to the html of the text-name. In this way, one can select items and benefit from the sankey-highlighting of items after the select-event and still be able to navigate to the visualization of the subcorpora! 
BTW: Orna think my new visualization is somewhat slower then what Kiyonori created earlier. How do you feel about this? I benchmarked both versions carefully on my system (as a reference, his version is still online here: http://buddhist-db.de/buddhnet/show.html) and couldn't observe a notable difference. How do you feel about this?

**Comment by ayya-vimala** [comment]
I like it very much now.
I've put the css in a separate file and made a few files for the hack to put it into an iframe on the frontend. It is there now. I don't have the feeling it is noticeably slower.
Maybe next week I will see how to make that into the webcomponent version of the same thing so I can do away with the iframe. Should be fairly straightforward, just using the same code you already wrote.
Will have to study how it does those tooltips and how to change that. But it's looking really good now!

It will indeed be good if you can go to the lower levels. Maybe I will wait until you are completely finished before moving it over to a webcomponent version.

**Comment by sebastian-nehrdich** [comment]
It might be the case that Kiyonori's version, since it is based on well-tested d3js, might be more stable after all. With web components I have the feeling that we sometimes venture into areas where not so much debugging has been done yet and things can behave a bit different. But I think all in all the speed is acceptable, at least on my system!
Anyway I think speed issues occur only on those cases where we are visualizing hundreds of files or more (like in the case of RGYUD). I still think that these visualizations are not extremely useful, it's just a bit too much information and it becomes hard to make sense of it. It works well in those cases where the canons are reasonably small, like MNGON PA. But I think this is less a technical issue but more a question on how we organize the files and the data and I might have to discuss with Orna and Dorji to see what their oppinion on this is. 

I have once more updated the visualization just now. I added a third layer which displays the statistics of an invididual file. so if you click on T06TD4064E in the visualization, you should get another diagram showing just the connections for this file. I thought it could be an useful addition because it's not always easy to grasp this information from the previous diagram! 
I only updated google_test.html and the sankey-directory. I also uploaded the new version to buddhist-db:  http://buddhist-db.de/visualization/test_google.html
Since I had to change the JS a bit to make this work, you might have to update the html-files of the hack to make this work!

**Comment by ayya-vimala** [comment]
It works also in the visualization in the frontend and today it's not slow so it must be my connection.
Your visualization using your test_google also works on http://buddhist-db.de/vimala/visualization/test_google.html
Only one request: if you make changes to the files, can you upload them to that visualization directory. There were around 12000 of them (although most just a few kb) and not any more to github. I think on GitHub they are not really needed.

Good work btw. It looks brilliant!
Will talk tomorrow 12 noon hangout on how to proceed for future.
