### ISSUE TITLE
Loading long Tibetan texts crashes the system

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#40]
#### Bug Description
Loading Tibetan texts of which the json exceeds something like 4MB crashes the system.

#### Steps To Reproduce:

1. Go to 'Tibetan' tab
2. Click on 'TD1097E'
3. It conitues loading but in the console it shows it has crashed with an error:

**updating-element.js:466 Uncaught (in promise) RangeError: Maximum call stack size exceeded**
 
#### Expected behaviour
Loading texts should not crash the system. I will have to ask outside help for this one.

**Comment by ayya-vimala** [comment]
Update: if you wait long enough and don't press any additional buttons it seems to work. Still, it is not ideal. Some kind of solution should be found.

**Comment by sebastian-nehrdich** [comment]
I think we are hitting a structural problem here due to the size of our data. Some of the larger Abhidharma-Texts (like the Abhidharma-kośa-commentaries in Tibetan) can easily reach more than 10 MB with their quotations. This will result in huge loading times unfortunately but given our situation we cannot do muvvh better at the moment I think. I would really opt for moving to a database in the long run. But this are all issues that have to do with the question how this project will continue in the future and if we can get backend developer that can deal with this in a professional way.

**Comment by ayya-vimala** [comment]
I was also thinking about  a virtual scroller. Something like Polymer's iron-lists.
Another one is here: https://github.com/Polymer/pwa-starter-kit/issues/119
https://www.npmjs.com/package/@polymer/iron-list

**Comment by sebastian-nehrdich** [comment]
That looks like a viable solution. One possible drawback of iron-lists is that we loose the option for the user to search the whole text by using the search function of the webbrowser. But I think regarding any serious kind of search functionality, we should move our project to a database anyway. 
In my opinion, for Paris and the near future this should not be a big issue, but a long-term solution is desired!

**Comment by sebastian-nehrdich** [comment]
I fixed the crash issue today by changing:
    suttaItem = html`${suttaItem} <span class="sutta-segment no-parallels" id="${i}">${dataSegment}</span>`
to
            suttaItems.push(html`<span class="sutta-segment no-parallels" id="${i}">${dataSegment}</span>`)
and having suttaItems as a dictionary. In the previous version, each time a new root segment got added the renderer was called and this stalled the whole rendering process of larger files. By using the dictionary and calling that in the lit-html templace simply by ${suttaIems}, this doesn't happen anymore. We still have the bandwidth problem though (can't get around this easily), but rendering of large files is now really much more responsive.  
I only changed it for tibetan-table-view.js for the time being.

**Comment by sebastian-nehrdich** [comment]
I am also 80% sure that a similar issue is causing the long loading times with the menus. So there is hope that we can optimize this. :)

**Comment by ayya-vimala** [comment]
That's great you found a solution and thanks for looking into it.
It did cause a lot of merge conflicts however because I had not pushed all new changes (had only uploaded it to the server but not to Git) so I'm not sure if it will all work now with the resolution of the conflicts. I had made a lot of changes to that part of the code already for the highlighting so had to undo a lot of that. I have not tested if it all works still .. will do tomorrow.
So next time you want to make or suggest a change, can you please do it on a separate branch and create a pull request rather than push to master? Thanks!

**Comment by sebastian-nehrdich** [comment]
Yes sorry for this! It was not my intention to disturb your workflow. 
I think also that we might be able to solve the problem of the rendering speed of the large files in the long run by partly doing server side rendering instead of moving all the data at once.
But this might also be something further down the roadmap. I am not so experienced with node.js development but as far as I understand it that's precisely the point of having node.js, to make these kind of things easy to implement. 
Technically speaking, the raw text (just the root segment entries in the leftmost column) of our longest files are about 1-2mb. In the text-view mode, we might render the quotes on the server side just on demand, e.g. when the user clicks on a passage instead of rendering everything at once.  This will save us about 70% of the traffic. We can't do that in the table view mode, however. 
But I think moving data that is less then let's so 5-10mb shouldn't be a big deal and we don't have to over-optimize things. I think in 2019, loading 5-10mb for displaying a huge set of information is totally acceptable...

**Comment by ayya-vimala** [comment]
I had a look at this and it is indeed a good solution. I will look more into it because there are still a few other parts where the stalling happens. One thing is the data that is loaded in the right column, when moved to the left, is reloaded and that is not needed.

The menu is slightly different.

In the long run I think using a database like ArangoDB/MongoDB would be even better. That way it will only give back the data that is needed at the time it is needed and not load the whole thing at once. For instance it will only give the data of the parallels of that specific segment when somebody clicks on that, and not load all parallels of all segments at once.

I've also been looking at this one: https://github.com/suttacentral/suttacentral/blob/master/client/utils/partitionAsync.js which just loads the data for the viewport so that's much quicker.

**Comment by ayya-vimala** [comment]
Although this is pushed, it can be better still with any of the above measures so I will make a new issue for that for reminding us later.
