### ISSUE TITLE
New JSON files to replace CSV

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#43]
(following is the post I made in the discussion on the data generation, but I think it is worth a seperate issue. I have implemented that now and the new files are online (both for Sanskrit and Tibetan. They are much simpler than the csv files and using json at this stage already should also simplify your workflow Vimala. I hope this change does not irritate you.
I already discovered a bug in the new Sanskrit jsons, but had no time to look into it yet. This issue is to document the progress of the change to the JSON files, including the changes necessary in the UI. )

Yes I see what you mean (and meditation usually brings about the best ideas anyway!). I did something very similar when I was working on the JQUERY frontend.
(below I use the word 'root segment' to describe the segments in the leftmost column; I will now make an issue about naming of things in the interface so that we both have an overview of what we are talking about): 

However, I see a potential disaster on the horizon waiting for us (excuse me the long post, I had to bring down all my thoughts about this):
The segmentation of the bilingual texts and the monolingual quotations will not match up. 
So currently we have the case where a root segment a and a root segment b are pulled together in the root-entry (a+b). We might segment that and work with arrays to fix the issue as you suggested and as I also did before.  
Imagine now we have the Tibetan root text like it is right now:
segment a+b
segment c+d
segment e (longer segment more than 8 words)
segment f+g
Now the Sanskrit texts wants to match with these matches but it is asking for the Tibetan segments:
segment b+c
segment e+f
And so on. I am afraid that this could turn into a big problem if we want to provide more or less precise Sanskrit<>Tibetan matches. I am therefore inclined to do what I described in the earlier post, because if each segment in the root-text is independent, then the Sanskrit can ask for any combination of root segments. 
However a new problem arises: Imagine the Sanskrit (or Tibetan) quote/translation are much longer than the Tibetan segment (they might easily span multiple lines). In that case, we need to assign one quote to multiple root segments. 
A cheap and low-work solution for both of us is just to copy each quote as many times as we have root segments. So imagine we have a long_quote_b(3 segments), then the resulting csv table could look like this::
segment_a long_quote_b
segment_b long_quote_b
segment_c long_quote_b

This solution will make the frontend behave precisely as we want it to behave. The big issue here is however that it creates a lot of unnecessary overhead (all the copied quotes are just creating even more traffic and bring the webbrowser close to crashing/OOM issues). 
One way to go about this: Mention each quote only once in the csv-file, but keep a list of the root-segments with the quote that indicates where it should match. Then we can generate a dictionary with all the quotes and iterate over the source segments on runtime and pull the quotes as we need them.
In order to make life easier for you, I can change the output of my neuronal networks so that it directly writes into JSON. I imagine it would make sense to have one dictionary for the root segments and one dictionary for the quotes. What do you think about this solution?

_Originally posted by @sebastian-nehrdich in https://github.com/ayya-vimala/pali-networks/issues/10#issuecomment-504639281_

**Comment by sebastian-nehrdich** [comment]
I am now working on it.

**Comment by sebastian-nehrdich** [comment]
As I mentioned in the mail, I have now finished the major part of rewriting the table-views for Tibetan so it works with the new jSON files. I will put this in a seperate branch today. My JSONS don't have any key names in order to save size - I have removed everything that is potencially not necessary and the size of the JSON-folder has thus been reduced from ~400mb to ~250mb. But it makes them a bit harder to read I guess.

**Comment by ayya-vimala** [comment]
I had a look but to be honest, I really don't like making the json files like this because they are no longer human readable. Again, in the long run you would want to have Arango/MongoDB that creates the json files and then the problem of large files is solved. But in the mean time, I think we should not take such shortcuts at at the expense of readability, which will create problems for the long run.

When I worked with the development firm they very much stressed the importance of code being able to be read by others and also json files to be used as intended, with a combination of objects (dictionaries) and arrays (lists). Lists are only used when real lists of items is meant. You don't put different multiple things in a list. And objects are needed to define what is what exactly in terms that make it very clear what is meant. So when somebody opens a json, they should be able to see what is a segment, what is it's number and what are the parallels attached to that.
I know that at the moment this makes things much bigger because you have all the labels but in the long run, when using ArangoDB/MongoDB it does not do that any more because those DB just filter out exactly what elements are needed and give you back only very compact json files with just those data and nothing too much.

One thing that was also stressed very much is making it very readable, if necessary with longer names to things. So in the frontend it is better to call `data.segment` than `data[0]` for instance. Or `data.parallels[0]` would mean the first parallel of thet data instead of something like `data[0][3][0]` which is abacradabra if somebody else tries to read it.

**Comment by sebastian-nehrdich** [comment]
I have just pushed new json-files into data-incoming/tibetan/json. Please have a look if this is how you can work with them well. I have now worked by duplicating the multiple-segment-quotes for each segment that is linked with them. It's not a very efficient solution but it works. 
Also i fixed the bug that we discovered today during skype. 
But there are still some problems remaining with the alignment of the quotes to the segment, sometimes they end up at an undesired position, either segment too early or too late. It's now getting a bit late for me to think clearly, so I will look into it tomorrow again.

**Comment by ayya-vimala** [comment]
It's pas 1am!!!! :-)
Sure, will have a look. Working goes better than meditating in this heat.

**Comment by ayya-vimala** [comment]
Just a couple of questions.
Why is the whole lot  wrapped in 2 lists rather than just one? I think you can loose the outer square brackets `[ ]`

What exactly is 'unsandied'? An how is that to be used?

> I have now worked by duplicating the multiple-segment-quotes for each segment that is linked with them. It's not a very efficient solution but it works.

This I'm a bit worried about: it creates unnecessary double data and bigger files.
Is it not possible to do it like I did before with for instance in TD4021:

> 
>         {
>             "segmentnr": 2,
>             "segment_unsandhied": "rgya gar skad dhy'anta bham k'a ",
>             "segment": " rgya gar skad du /",
>             "parallels": [
>                 {
>                     "probability": 0.020659804,
>                     "parsegnr": [
>                         "T06TD4032E:2",
>                         "T06TD4032E:3"
>                     ],
>                     "parunsandhied": "bham t'i k'a bod skad dbus ",
>                     "parsegment": [
>                         " ma dhyan nta bi bham ga t'i k'a / ",
>                         "bod skad du /"
>                     ]
>                 },
>                 {
>                     "probability": 0.028162837,
>                     "parsegnr": [
>                         "T06TD4055E:1",
>                         "T06TD4055E:2"
>                     ],
>                     "parunsandhied": "gar skad tring shi k'a k'a ",
>                     "parsegment": [
>                         " rgya gar skad du / ",
>                         "tring shi ka k'a ri k'a /"
>                     ]
>                 }
>             ]
>         },
>         {
>             "segmentnr": 3,
>             "segment_unsandhied": "rgya gar skad dhy'anta bham k'a ",
>             "segment": "ma dhy'anta bi bham ga k'a ri k'a /",
>             "parallels": [
>                 {
>                     "probability": 0.020659804,
>                     "parsegnr": [
>                         "T06TD4032E:2",
>                         "T06TD4032E:3"
>                     ],
>                     "parunsandhied": "bham t'i k'a bod skad dbus ",
>                     "parsegment": [
>                         " ma dhyan nta bi bham ga t'i k'a / ",
>                         "bod skad du /"
>                     ]
>                 },
>                 {
>                     "probability": 0.028162837,
>                     "parsegnr": [
>                         "T06TD4055E:1",
>                         "T06TD4055E:2"
>                     ],
>                     "parunsandhied": "gar skad tring shi k'a k'a ",
>                     "parsegment": [
>                         " rgya gar skad du / ",
>                         "tring shi ka k'a ri k'a /"
>                     ]
>                 }
>             ]
>         },

To become:

> 
>         {
>             "segmentnr": [2,3],
>             "segment_unsandhied": "rgya gar skad dhy'anta bham k'a ",
>             "segment": [" rgya gar skad du /",
>                                 "ma dhy'anta bi bham ga k'a ri k'a /"]
>             "parallels": [
>                 {
>                     "probability": 0.020659804,
>                     "parsegnr": [
>                         "T06TD4032E:2",
>                         "T06TD4032E:3"
>                     ],
>                     "parunsandhied": "bham t'i k'a bod skad dbus ",
>                     "parsegment": [
>                         " ma dhyan nta bi bham ga t'i k'a / ",
>                         "bod skad du /"
>                     ]
>                 },
>                 {
>                     "probability": 0.028162837,
>                     "parsegnr": [
>                         "T06TD4055E:1",
>                         "T06TD4055E:2"
>                     ],
>                     "parunsandhied": "gar skad tring shi k'a k'a ",
>                     "parsegment": [
>                         " rgya gar skad du / ",
>                         "tring shi ka k'a ri k'a /"
>                     ]
>                 }
>             ]
>         },
>

**Comment by ayya-vimala** [comment]
Never my my remark about unsandied ... I noticed you removed it in the last update.
Will try it all tomorrow ...

**Comment by sebastian-nehrdich** [comment]
Yes your suggestion is of course possible. This will save us some space but as I mentioned before, it will make things a bit more complicated if we add the Sanskrit, because the Sanskrit will require different combinations of root segments than is the case for the Tibetan. 
However it could work if we keep the Sanskrit data in a seperate file and do a bit more of work on the frontend level. I will upload an example soon so you can get a picture what I mean.

**Comment by sebastian-nehrdich** [comment]
I have now uploaded json-files with the changes that you suggested. This means that I cannot add the Sanskrit directly but we have to go another route by storing them in a seperate JSON and then have to insert them at display-time. Let me hear how you feel about this!

**Comment by ayya-vimala** [comment]
Oops, yes, I forgot about the Sanskrit ones. Indeed you are right. I just had in mind the length of the parallels both in terms of the file-size as well as in the counter which I have now installed (doubling up the parallels in that also doubles up the count of them, but that is probably not that problematic anyway because it just changes how you count things).

First as to the structure of the JSON files of the Tibetan texts: There is still a list element too many as it is now a list of objects in another list which just has just the one list in it. It seems to be the case for everything. Just the list of objects itself is enough.
Then the first object is always empty. That is not needed. Not a real problem either because I can just iterate starting from 1 rather than from 0, but it's just not very nice. Or is there a good reason for this being there?

With regards to the Sanskrit and how to do it properly ...  that is indeed a very good point.
I'm sorry I did not think about it that the Sanskrit of course has different numbers/segments. Maybe your first idea to double things up is the best after all ... that would be the least confusing. Also because we have to think about how it is the other way around i.e. what happens when I choose a Sanskrit file to show the Tibetan as parallels to that ... And also in the long run, when we have links to maybe pali.

I'm really sorry to cause you more work. But it is good to see it in front of me.

So if I understand you correctly, your initial idea was to have it like this:

>         {
>             "segmentnr": 3
>             "segment": " bod skad du /"
>             "parallels": [
>                 {
>                     "probability": 1.1920929e-07,
>                     "parsegnr": [
>                         "P#1_0"
>                     ],
>                     "parsegment": [
>                         "namaH budDAya+"
>                     ]
>                  },
>             ]
>         },

And then basically the same for segments 2, 4, 5 and 6.
You are probably right that that in the long run is the easiest for everyone, even though the files will be a bit bigger.
(note that the Sanskrit is still in it's tokanized form)

**Comment by sebastian-nehrdich** [comment]
One way to do this (which will slightly decrease the readability of the json) is to define a parallel-dictionary separately from the segments where each parallel is stored with an unique identifier. So instead of each time having the entire parallel for each segment under 'parallels', we just refer to the id, which then can be looked up in the dictionary. What do you think? It's a cheap alternative do a database and could be a 'hack' until we implement it properly.

**Comment by ayya-vimala** [comment]
What we do in SC (which is input in ArangoDB) is we have files that have the segments, say for instance the file T06TD4046E would be:

> [
>   { "T06TD4064E:7" : "gang-zag dang chos la bdag  med-pa ma-rtogs-pa dang log-par rtogs-pa rnams la gang-zag dang chos-la-bdag-med-pa ma-log-par bstan-pa'i phyir /" },
>   { "T06TD4064E:8" : "rnam-par-rig-pa'i rab tu byed-pa sum cu pa brtsams so //" },
>   { etc ... }
> ]

(so the filename repeats with the segment number in the file itself so as to make it unique)
And then the same for the Sanskrit.

And then a second file parallels.json that says things like:

> [
>     ["T06TD4064E:7","sthtvbhu:P#2.0","T06TD4070E:76", etc.],
>     ["T06TD4064E:8","sthtvbhu:P#2.0"],
>     [ etc.... ]
> ]

(in this case it would mean that the parallel is reversable. So if A is parallel to B, B is parallel to A.)

The second file becomes absolutely huge, but only with numbers. So that way you do not double up on the whole segment text somewhere. When you call on Arango, you just ask: give me all parallels that have T06TD4064E:7 for instance. And then it gives you that.

You don't need an unique identifyer: you already have one, namely the file:segment number.

For us however that would not work because we do not have a database, even if we put the numbers in a separate file per text because for instance for the segment view, you would still need to read all the files that it has segments with also to get the text with that parallel segment. So if text A has parallels to for instance B, C, D, E and F, you would end up reading 7 json files altogether and that would get very slow.

So if you make 2 files you need to double up on the parsegment texts: it needs to be listed with the parallel AND as a segment in the main file. 

So the json files I originally made were for use with the segmented view only. It has exactly all the info that that view needs and nothing more. For the number-view, you basically need the same but just the numbers.

For the text-view however it is a bit different. You need in first instance just to show the text. But everybody will want to see the parallels too so without a database, you will also need to read a file with the parallels in it. So again, you need all the info there. So there is no point splitting the two files because that is just doubling up on information. You need to have all the info there so you might as well do it in the same one.

So to me it seems that we really need one file per text with all the info in it, so also the parallels listed in it.

So the above is just my thinking ... we can talk about it after the SC meeting in about an hour if you want.

**Comment by ayya-vimala** [comment]
It seems to me that whatever we do it is going to be a decision and nothing is going to be the perfect answer. The further we go the more I think we really need to database BUT AFTER PARIS. So for now, I suggest to just keep it in one file and then we can restructure after.

**Comment by sebastian-nehrdich** [comment]
Yes I agree with you, also regarding the ideal layout of a database, that all makes sense and would be the way to go.
I was thinking, in order to save space within one json file, we could do the following: 
`        {
            "segmentnr": [
                7
            ],
            "segment": [
                " gang-zag dang chos la bdag  med-pa ma-rtogs-pa dang log-par rtogs-pa rnams la gang-zag dang chos-la-bdag-med-pa ma-log-par bstan-pa'i phyir /"
            ],
            "parallels": [ 1,2]
}
`
And then a second dictionary defined in the same json: 
`            "parallels": [
{ 1:
                {
                    "probability": 1.1920929e-07,
                    "parsegnr": [
                        "T06TD4070E:76"
                    ],
                    "parsegment": [
                        "de ni 'di  skad du sems-can gang dag gang-zag dang chos-la-bdag-med-par mi-shes-pa rnams dang  gang dag dogs-pa rnams dang  gang dag phyin-ci-log tu gyur-pa de-dag la gang-zag dang chos-la-bdag-med-pa ma-log-par bstan-pa'i phyir rnam-par-rig-pa'i rab tu byed-pa sum cu pa brtsams so  zhes bstan-par 'gyur ro //"
                    ]
                },

2:             {
                    "probability": 0.023904443,
                    "parsegnr": [
                        "T06TD4034.1E:7765"
                    ],
                    "parsegment": [
                        " bdag dang sems-can-thams-cad kyi don-bya-ba rtogs-pa dang  gang-zag dang chos-la-bdag-med-par rtogs-pa'i  phyir ro //"
                    ]
                },
`
and so on. When you then read in these files in the frontend, you need to expand each number with the value from the dictionary. This is a cheap compression, no need for keeping large lists or seperate files.  Otherwise we could just stick to the duplications, which is also fine with me - just let me know what you prefer.

**Comment by ayya-vimala** [comment]
I wonder if this really makes much difference but we can try.
The only difference is that you don't put the same parallel with the same probability in it twice. So parallel number 1 can for instance appear twice with 2 different segments. I think that is why you want to do this right? So as not to double up on the parallels in the json file (although it will still double up in the parallel-count but I think that is defendable because it is really two different parallels if you look at it from that angle).

I just hope that the extra work this will be for the frontend will not slow things down again. 
That is also why I have made a shortcut in the menu structure that basically reads the whole menu dropdown as one string rather than iterate over each file to create it. It's a longer file to load but it saves some 7000 iterations for the pali alone.

So I think that what you win somewhere, you loose somewhere else. But we can try and see.
What do you think?

Also, what is best for your own sankey-json files you need?

**Comment by sebastian-nehrdich** [comment]
I just checked and its a difference of about 50% (250mb vs. 380mb for the dataset that we are working on atm). We could just go with the duplicates and see how it is going to behave regarding the bandwidth. If we run into problems than we could optimize this. 
Generally speaking dictionaries are hashed, so there should be no performance loss when calling them. But on the other hand I see the point that it is increasing complexity on the frontend level. 
It totally doesn't matter for me, I am collecting my data on an earlier stage (combining quotes etc. distorts the statistics anyway, that's why I like to do it before). 
But the question remains whether you would like to have the Sanskrit in the same file or in a seperate file. For me, both is fine!

**Comment by ayya-vimala** [comment]
In that case, let's just go with what you did before ie. doubling them up, having it in the same format.
And yes, the Sanskrit parallels in the same way, in the same file, as the first one in the list of parallels, would be great.

Thanks for doing it and I'm sorry if I'm a bit not quite there today. I have a heavy migraine ... :-(

Just remove the extra [] and the first one of the segments if that one is empty without any number.

**Comment by sebastian-nehrdich** [comment]
no problem! That's all fine with me. Yes I think if we start optimizing things at this stage it will just amount to more work in the long run, as Knuth said, 'premature optimization is the root of all evil'. :)
I will do your proposed changes and upload the new version of the files.
By the way, should we have a 'langid' for each segment (so that we for example could do a slight visual distinction by having a different background color for the sanskrit or something like that). I think a langid would be also necessary in the case of a database to keep things tidy...

**Comment by ayya-vimala** [comment]
I think at this stage it is clear what language something is from just looking at the segment ID. And not necessary for Paris. So let's wait with that too.
Never heard of Knuth (sounds like that Polar Bear :-)) but he is very right.

**Comment by sebastian-nehrdich** [comment]
OK! I just pushed the updated JSONS, I hope they are now better. Also I added the Sanskrit to T06TD4064.json, (in the tibetan/json folder), please have a look at it!

**Comment by sebastian-nehrdich** [comment]
Oh no, just found a bug, hold on... Fixing it now.

**Comment by ayya-vimala** [comment]
T06TD4064 looks fine, but you need an `encoding='utf-8'` in your python to get rid of all the `\u1e43\u015b` and just use utf-8 characters instead.

It might also be good to have it in the same format as the rest. Like probability, parsegnr and parsegment in that order but not a big deal of course.

**Comment by ayya-vimala** [comment]
BTW did you ask about the uppercase for TIbetan texts? Or shall I just make it lower case?

**Comment by ayya-vimala** [comment]
I tested the JSONS and they work just fine. Just some very slight adaptions were needed to the frontend and it is much easier on the highlighting, which works fine now (not yet on the buddhist-db site). It also does not seem to be too slow at all.
Now we have a structure to that, can you not upload them to data-incoming in GitHub (will become way too much unless we make a second repro called buddhist-texts or something like that). Better to upload it straight to buddhist-db.

What I would ideally want is to upload them to buddhist-db in my vimala folder under suttas in subfolders like:
T01
   T014000E
   etc.
T02
   files
T03
   files

And then also for the sanskrit that they get a name that has the number of the collection in front in those same folders. So if a sanskrit text abc is from collection T01, to name it T01abc.json in folder T01.
I just need some structure to find things back easily and putting everything in the same folder without a sub-structure seems a bit much.
What do you think?

I want to work on getting the Sanskrit menu next and getting those texts displayed and maybe get all of the Tibetan ones in too. So could you get me the data I need for the Sanskrit menu and also we need a decision on the above (file/directory structure).

**Comment by sebastian-nehrdich** [comment]
OK! I will do the adjustments that you suggested (UTF-8 + order of the entries)
The folder structure is totally fine with me, I can take care of that. I wanted to ask you exactly the same thing about buddhist-db.de - because right now I want to start to generate the entire data (both GRETIL as well as Tengyur/Kangyur) and then our github will become too small.
So I will put them straight under vimala/suttas/ and then with the appropiate subfolder for each category (T01 etc), right?  Do you want to divide them by language? In not too far a future (probably end of July), I want to add the Chinese data and I am afraid that the folder structure of the Taishō is also something like T01 T02 and so on - maybe it's easier to have a basket for each language (and maybe additionally think about a different naming scheme for Chinese in order to avoid confusion, but that's further down the road and no topic at this point).

**Comment by ayya-vimala** [comment]
Yes, maybe you are right and to divide them by language. And in that case, maybe you were right the first time to have a language-identifyer in the files too for each parallel so it knows in which language under which folder and subfolder to find things without first having to search through the entire database to do find out where a certain file is stored.

So shall we say 4 folders:

> Tibetan
> ----T01
> ----T02
> ----etc.
> Sanskrit
> ----T01
> ----T02
> ----etc.
> Pali
> ----MN
> ----DN
> ----etc.
> Chinese
> ----leave for now

And then for instance in Tibetan - T06 - T06TD4064E.json:

>     {
>         "segmentnr": 1,
>         "segment": " rgya gar skad du /",
>         "parallels": [
>             {
>                 "parsegment": [
>                     "Vasubandhu: Tri\u1e43\u015bik\u0101vij\u00f1aptik\u0101rik\u0101 /"
>                 ],
>                 "parsegnr": [
>                     "sthtvbhu:P#0_0"
>                 ],
>                 "probability": 0,
>                 "languageID": "san"
>             }
>         ]
>     },

**Comment by sebastian-nehrdich** [comment]
Yes I think a lang-id that is also visible in the frontend would be helpful in the long run. For example I am thinking about adding a sanskrit grammatical analyzer in the future time (based on our tokenizer) which might also have some dictionary functionality etc. and in that case we really want to know which language each segment has. In my eyes three-character identifiers would be nice, for example: "skt","tib", "pal","zhn". Does it look right to you?

**Comment by ayya-vimala** [comment]
From a SC standpoint we use "san",""xct", "pli" and "lzh" but I'm not attached to those ... whatever you think is best.

**Comment by sebastian-nehrdich** [comment]
we decided to leave the langid out due to file size concerncs. We might add that later. For the time being, this issue can be closed I think
