### ISSUE TITLE
Loading large texts and menus improvement

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#48]
The loading of large texts can do with improvement using queries to a database like ArangoDB or MongoDB as well as using visual synchronisation methods like SuttaCentral uses:
https://github.com/suttacentral/suttacentral/blob/master/client/utils/partitionAsync.js

**Comment by sebastian-nehrdich** [comment]
Currently some improvement with the initial startup of the page should be done. We are only transferring 200kb to the client, but it takes about 8sec to render! I suspect that these are the menus, but I am not sure. I will look into that a bit more into detail. Given the fact that the menus are static, we could even think about pre-rendering things  with something like headless-chrome or so in order to speed things up. But I also remember you mentioning that you want to replace the current menu display anyway with a more convenient side-bar - maybe in that case it wouldn't make so much sense to put effort into tuning the menus? What do you think?

**Comment by ayya-vimala** [comment]
The rendering of the startup has to do with iron-pages. It basically loads all the menus and everything at once and that slows down the system. It will be better when I install routing: then it will only render a page when it is called and not straight away: right now it renders all the pages, homepage, sanskrit, tibetan and visual page at the same time.

**Comment by sebastian-nehrdich** [comment]
Thank you for the explanation, it makes sense!

**Comment by sebastian-nehrdich** [comment]
Should we close this? I have the feeling this has now been distributed over other issues and is not relevant as such anymore.
