### ISSUE TITLE
Highlighting segments

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#53]
Make sure segment highlighting in text mode works for Sanskrit as well, especially with the new segment numbers.

**Comment by ayya-vimala** [comment]
The highlighting in the text-view mostly works except for ranges in the Sanskrit files. I will have to change the structure on how parallel ranges are calculated and was thinking of a system that just lists all of the parallels in a line rather than the beginning and end one. So instead of `P:0_0--3_0` to list `P:0_0, LG:Mvk123_12, P:2_0, LG:Mvk345_53, P:3_0`. That would also overcome the issue with the different types of line numbers albeit it looks a little bit more scruffy.

**Comment by sebastian-nehrdich** [comment]
I just exchanged mails with Orna and the current situation is: 
Due to the addition of the Sanskrit, all the text on the left side has turned blue and we can therefore not see anymore where there are parallels and where not! can we change this for Paris so that at least the Sanskrit is ignored for the higlighting (same the other way round, so when the root-text is Sanskrit the Tibetan parallels should be ignored).

**Comment by ayya-vimala** [comment]
No, I changed the color of the parallels around: blue is parallels, black is no parallels. And I can see it very well. I thought you might want it turned around. It also says in the subject line:

> Click on a segment in the text to display the parallels. Only blue text has parallels. Black text has no parallels. If you have applied a filter, not all possible parallels will show up

![Screenshot from 2019-07-05 15-44-36](https://user-images.githubusercontent.com/49606945/60726439-d52e9f00-9f3b-11e9-9d4b-bc051a7dcb39.png)

**Comment by ayya-vimala** [comment]
I don't quite understand what you are saying. It works for me for all parallels, sanskrit to tibetan and visa versa as well as sanskrit to sanskrit and tibetan to tibetan.

**Comment by ayya-vimala** [comment]
When I talk about highlighting, it is the orange highlighting on the right side after a parallels is selected. It then scrolls to that. That works well for Tibetan texts (which has sequential numbers for the segments) but for the Sanskrit it only highlights the first segment in a range and not all of them. So if there is no range but just one parallel segment, it works fine.
But I want to make it so that it also highlights all the segments in a range.

**Comment by sebastian-nehrdich** [comment]
Oh I am sorry for being unclear: I mean that when one initially opens the file, now in the case of TD4064, everything is blue in the left column. That is right because everything has a Sanskrit parallel. But this is inconvenient for the user: It would be better to ignore the Sanskrit in this case and only make that text blue that also has a Tibetan parallel! 
![screen_highlight](https://user-images.githubusercontent.com/18755480/60727063-f9a86c80-9f77-11e9-9584-c6e37bf9be77.png)

**Comment by sebastian-nehrdich** [comment]
This is the only thing we should fix for Paris, everything else is OK. If you can't take care of it because of your retreat, no problem, I can give it a shot and make a pull request later.

**Comment by ayya-vimala** [comment]
Ah yes, I see what you mean. These texts are literal translations of each other so they always have parallels no matter what ... have to think about how to do that because you also want to be able to click on the texts that only have a sanskrit parallel and no tibetan as you want to be able to see the sanskrit text as well. You don't want to have to find a segment that has a parallel with another Tibetan text in order to go and see the sanskrit ...
Moreover, right now it will be hard to figure out which one is tibetan and which one is sanskrit because we have not introduced the language code. I would have to perform a check on each parallel in each segment of the whole file and then recalculating the whole thing ...

**Comment by ayya-vimala** [comment]
One quick and dirty solution I can think about is to have text in blue only when there is more than one parallel. Then it does not check for sanskrit but goes from the premise that the first one is always the sanskrit. Might not work in all cases .... F.i. the screenshot I had above is also from a text that has a sanskrit parallel and some of those are black text.

**Comment by sebastian-nehrdich** [comment]
That could work for the time being, but we  have to check then if Sanskrit
parallels are present at all in order to avoid that the highlighting breaks
on texts without a Sanskrit parallel. Do you think that is possible?
One way would be to check if any segment-name in the json is present that
has a capital T and no TD or a capital K and no kl and no acip. Then we
know that Sanskrit is present and can thus ignore the case that only one
parallel is present.

**Comment by ayya-vimala** [comment]
I just looked at some and it is not very consistent (at least not in the text I checked which is T06bsa010_u.
I have another idea but for that I need some other data from you. Right now I have two files that show the multilingual files in Tibetan and Sanskrit. But they do not show which ones are related to which.
For instance, it is clear that T06bsa010_u is related to T06TD4021E from me looking at the results. If I have a list that shows something like "T06bsa010_u":"T06TD4021E" (or tabs or commas or anything else), then I can load that list and see if my file appears in that list and then just disregard all the parallels of that specific related sutta in the count.

I can namecheck (that I already do and there is a function for that) but you don't want to do that for all parallels in a file if at all possible because that will increase the loading time a lot. Some files have many parallels.

Still remains the question on what to do with the clicks. So you will have to be able to click on black text too? Or make that another color?

**Comment by ayya-vimala** [comment]
Anyway, will have a think about it (and meditate about it) and can probably do it on Sunday or monday.

**Comment by sebastian-nehrdich** [comment]
OK! Yes sure I can provide you with that data, I am keeping these lists anyway. If you need anything else just let me know. Will upload it tomorrow. 
(Enough for me today, I am finishing now, enjoy your retreat!)

**Comment by ayya-vimala** [comment]
Good night! I still have to prepare the retreat ... I'm conducting it myself.

**Comment by sebastian-nehrdich** [comment]
OK! I will also think about the problem tomorrow and then we can discuss it
on Sunday/Monday.
Enjoy the retreat!

**Comment by ayya-vimala** [comment]
Ha ... 10 minutes of meditation and I found it!!! Yeah!
I don't have to check for the other language for all parallels, only when there is only one parallel. So I will upload that in the next half hour.

**Comment by sebastian-nehrdich** [comment]
Great! I checked it and it works very well. Thank you very much for this!
I think we should be definitely spending more time on meditation. Seems to me as if the best ideas of the past weeks have been found during meditation... :) :)

**Comment by ayya-vimala** [comment]
Okay, highlighting works much better now. It will highlight all the segments that are part of the parallel and it seems to be much quicker too.

**Comment by sebastian-nehrdich** [comment]
That's good, I will check it out!
By the way during my meditation the past days it came to my mind that I want to change the way we do this. 
I am not all too happy by my practice of marking entire segments in the json output because we have frequently the case that segments get marked which only continue a very small fraction (or sometimes nothing at all) of the quote. This really annoys me. I think we can do better than that.
I would like to supply additional values for each segment which will contain 'offset beg' and 'offset end'.
Imagine we have a sentence that goes like:
bdag dang chos la nyer dogs pa 
'offset beg' : 2 now would mean that we start to count from 'chos and ignore the first two words. in the same way. 'offset end' : 2 would mean that we stop the highlighting after dogs pa.
With Sanskrit, this will be certainly more tricky. Here I cannot give the offset in word count but we might have to work with character positions, so in a nice long compound such as 'ātmadharmopacāro hi' I might give the offset as '8' and then we start to highlight from opacāro onwards. 
Anyway I will have to work out the details on how I will change the data the next days, I just wanted to warn you that some bigger change is going to happen! :)

**Comment by sebastian-nehrdich** [comment]
(and by the way, I checked the higlightling now and it looks very good to me with your recent changes! The speed of the text display is also very acceptable now. I think generally speaking, the responsiveness of our site even for larger texts with tens of thousands of quotations has become very good! It has become really usable now!)
