### ISSUE TITLE
Sanskrit parallel not scrolling

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#58]
#### Bug Description
The Sanskrit parallel to a Tibetan text is not scrolling to the right position on text view

#### Steps To Reproduce:
Open T06TD4064 in the menu, scroll down in text-view a bit (let's say scroll to 50%) and click on a sanskrit parallel - the right file opens (T06sthtvbhu), but it is not scrolling to the right segment (remains at the top)

**Comment by ayya-vimala** [comment]
I don't know. With me it works just fine. But "scroll into view" is what is marked in the issue #53 - the highlighting is not working completely yet - it only does it when it is not a range or otherwise just takes the first one of the range.
![Screenshot from 2019-07-05 10-44-41](https://user-images.githubusercontent.com/49606945/60710047-13af6400-9f12-11e9-9752-9f75dd35e2b3.png)
If you happen to have one where the parallel segment number does not match any segment number in the sanskrit text, then it will stay at the top.

So I'm afraid I cannot recreate the error here ... I've tried a large number of them and they all worked.

**Comment by ayya-vimala** [comment]
What does your console say?

**Comment by sebastian-nehrdich** [comment]
I think I got it now, sorry for my stupidity! I was clicking on the text of
the parallel (on the Sanskrit words themselves) and that doesn't scroll.
But when I click just on the name of the parallel on top of the css
element, that works actually.
If I click somewhere else in the element, scrolling fails with the error
message:
    main.d0530949.js:4310 Uncaught (in promise) TypeError: Cannot read
property 'scrollIntoView' of null
        at fetch.then.then.n (main.d0530949.js:4310)

I don't know if this is to be considered a bug or a feature - maybe would
be nice to work if somebody just clicks anywhere on the quote but it's not
a big issue I think. Just important that Orna knows about this!

**Comment by ayya-vimala** [comment]
I see, no the element uses the innerText property of the parallel to find out where to go. I will see if I can do something about that. Probably also because in the search results at SuttaCentral I initially made it with clicking on the whole text but Bhante Sujato said that that is not the proper way to do it and it should be the link itself only. I don't mind either way but I want to change the whole way in which the highlighting is done differently anyway.

**Comment by sebastian-nehrdich** [comment]
I trust your judgement on this!

**Comment by ayya-vimala** [comment]
The fact that it loads the page when clicking on the parallel segment is wrong. It has to be either one or the other and not half: you either click on the number and it loads and highlights and scrolls and does not do anything when you click on the text, or it does everything if you click anywhere in the parallel. Right now it is not logical. I will have a look next week. I have a retreat to prepare now. But Orna can just click on the parallel number for now to be sure.

**Comment by sebastian-nehrdich** [comment]
no problem with this! it's fine imho, leave it for later.
We do however now have a problem with the width of the right column when
displaying a longer sanskrit parallel, but that's another issue for later.

**Comment by ayya-vimala** [comment]
I think the problem with the right column width will disappear with better Gretil data. It has to do with very lenghty words and sentences. I already tried something that works most of the time. Can you give me a specific sequence where this happens?

**Comment by sebastian-nehrdich** [comment]
This is from T06vmvkbh_u: After clicking on the Sanskrit parallel that you can see in the screenshot (doesn't happen with Tibetan), the width of the entire page exceeds my screen width (which is already WQHD) and a scrollbar appears at the bottom. Width of all three windows is set too far in this case, not so good imho! But I am not so sure if this is only because of the right column, could be that the column-size bug we had earlier is also in play here. 
![screen_fail png](https://user-images.githubusercontent.com/18755480/60728570-9e787900-9f7b-11e9-8831-48c5784dc8d6.png)

**Comment by ayya-vimala** [comment]
This issue unfortunately has to do with breaking Sanskrit words. I will have a look to see if I can force it to break.

**Comment by sebastian-nehrdich** [comment]
CSS and Sanskrit sandhied long string is a lot of fun, I remember that. Probably feels like passing through another (less severe) naraka at this point. As I mentioned on Skype, ideally we need some dedicated rules for Sanskrit separation, but that's a whole other issue...

**Comment by ayya-vimala** [comment]
I found something here too. Will upload it soon too.

**Comment by sebastian-nehrdich** [comment]
You already uploaded it, right? 
I just checked it and it seems to work fine now. The problems I observed yesterday have largely disappeared. The only thing that remains now is the old bug with the size of the separators jumping a bit when opening a parallel for the first time but this is not a big problem imho.
Should I close this?
