### ISSUE TITLE
Create JSON files with offset properties

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#62]
Offset properties will make the occurance of parallels within segments more obvious.
By indicating where a parallel starts and ends, it is possible to be more precise than is currently the case.

**Comment by sebastian-nehrdich** [comment]
I have now created a small batch of the new json files for our testing purpose, they lie on the server under suttas_new (currently only tibetan/T06 is available). 
The changes are as follows:
- each parallel is only mentioned once, and it is mentioned in the segment where it occurs for the first time (even though the larger part of that parallel might actually not relate to the segment of the root-text where it appeared for the first time)
- each parallel now has the following additional values: 
  - "length" is indicating the length of the matched sequence (at least 6 words because that is the minimum length of a segment in my algorithm, but it can be much longer)
  - "par_offset_beg" this is the offset from which the match starts in the first segment of the parallel. value is given as a character position and counted from the beginning of the string. So if the string is ""chos shes pa mngon par 'du byed pa", a par_offset_beg of 10 would mean to highlight from "pa" onwards"
  - "par_offset_end" means the position of the last segment in the parallel where the highlighting should stop. 
  - "root_offset_beg" and "root_offset_end" are the values in the same format but now they refer to the root segment on the left side 

This new format requires us to make some serious changes to the text-view and the table-view. I will create seperate issues for these.

**Comment by ayya-vimala** [comment]
One thing that might become confusing is the designation of "last" parallel segment. What if these numbers are not in the right order as it sometimes is, especially for the sanskrit files. Would it not be easier to say:
`parsegnr: [[T064021E:5,5,-1][T064021E:6,0,-1][T064021E:7,0,6]]` or something like that so it is clear which part of which segment is what.

**Comment by sebastian-nehrdich** [comment]
the issue with the ordering *should* be fixed with the newer files (but we
never know). Let's check out if we run into problems and if so, I will add
the additional values as you suggested, ok?

**Comment by ayya-vimala** [comment]
I've added some small changes to the json files in issue #63 so as to make it consistent with the json files we had so as not to break anything somewhere else. Other than that it should work fine now.

**Comment by sebastian-nehrdich** [comment]
OK! I have implemented your changes in the new generation of filesand also made some changes to the folder structure. I will upload the new code and files today in the (Japanese) evening to a separate branch. 
Generally speaking, debugging the offset values was extremely hairy and took me at least 20 hours of looking for the needle(s) in the haystack. It's not perfect yet but I think it's good to go so we have something solid that we can work with for the next weeks and months.

**Comment by ayya-vimala** [comment]
What I would prefer to do is look at your code and incorporate it into the main branch bit by bit so I know what is going on rather than merge the branches and then try to find all the problems afterwards. But I think it is easiest if you focus on creating the json files. I looked around but I cannot find them so I guess you have not uploaded them yet. I cannot do anything until I have the jsons.

**Comment by sebastian-nehrdich** [comment]
I just uploaded the files to the server. I replaced the content of suttas_new with the new files. I had to do some changes to the source in order to make it work, these changes are in the new branch highlighting-sebastian. At the moment, the scrolling to the right position in the text on the right side (third column) is broken, haven't looked into this yet. 
The jsons now still continue a lot of unncessary entries which I added to make the debugging easier. I will remove them later, so please just ignore any entry that looks strange/unfamiliar to you.

**Comment by ayya-vimala** [comment]
I will have a look tomorrow and start to merge it. Right now trying to upload the Sankey webcomponent to the server ... takes a bit of time.
Yes please change the jsons to reflect how you want them.
Do we have a meeting on Tuesday?

**Comment by sebastian-nehrdich** [comment]
Depends on how much we have to discuss - from my side we don't need to because I was mainly busy with my stuff (debugging jsons and thinking about the Chinese) and there is not so much team-relevant stuff on the horizon yet. I am now translating the contract to English so that we can get Hubert into the team very soon. Orna is now slowly starting to analyze and evaluate the website, so maybe during the next week some more things will come up and having a hangout somewhat later (end of the week or beginning of next-next week so around the 29th or so) would make sense imho. Or what do you think?

**Comment by ayya-vimala** [comment]
Okay, I will take a few days to look at the highlighting and to see what you have done.

**Comment by ayya-vimala** [comment]
There are a few initial things I noticed so just want to ask you about that:
So when I open T06TD4021E, it shows me the file with some parallels in blue. These are not the same ones as we had before and the sanskrit ones are gone too. Why is this?

When I click on the first blue part (MTSHAN NYID SGRIB PA DE KHO NA ||), in the old version it shows me parallel T06TD4027E:12–14. Now I get T06TD4027E:12#12#12–15#-1#-1, which looks really weird (and is obviously wrong somewhere) and no wonder the scrolling is not working. I can fix that.

So some questions arise here:
	1. Why not keep it in the old format and not mention the highlighted part in the title: that is cleaner and clear from the highlighted part already.
	2. Why is it suddently 12-15 as before it was 12-14?

It is generating the whole menu again x times but I guess that's because you made a branch before I fixed that.

**Comment by sebastian-nehrdich** [comment]
yes I branched this off from your highlightning-branch earlier so the fix regarding the menus is not in yet!
I have made some major changes to the algorithm. The Sanskrit is gone for the time being and I will only add that again when we got the matching for the Tibetan as good as possible (which is not yet the case). 
So for the time of debugging and fixing, there will be no Sanskrit. At the moment nobody should be using the website anyway (apart from us), so that should not be a concern. 
I have reduced the minimum parallel segment size from 6 to four words and this is why the blue  highlighting has changed a lot to what we had before. Also I have implement a function to merge continuous quotes globally and not just within one segment, which required a major change of the algorithm but also means that we get more consisten results.
Finally in order to save time I limited this to a testing corpus that only has material from T06 so I can calculate new quotes after changing the algorithm without having to wait 6 hours for the results to come. Once we got the paramaters right I will run this again through the entire data that we have.  

Regarding 1) I don't clearly understand what you mean by this. could you maybe point me out the corresponding position in the JSON where you think something has changed to the worse?

Regarding 2) because 12-14 was wrong. The quote runs over four segments. So we want this to to be 12-15 ideally!

Currently, especially the root_segnr need some more debugging, I know that something still is off here. I am having an eye on this.

**Comment by ayya-vimala** [comment]
Okay, so you are saying you just ran the system with a subset for testing. Makes sense. Thanks for the explanations and I don't quite know how the neuronal network works.

But a weird thing happened. I just went back to look things up again and now the title has changed to 12-15 without the whole offset added to it. I don't know why the first time it gave me that and not now. The first time it gave me `T06TD4027E:12#12#12–15#-1#-1` now it shows `T06TD4027E:12–15`, running the same branch. Will have to keep a lookout for that ... 
In any case, it is not an error in the json files so I will try to find what it is and merge things slowly.
Did you still want to have jsons for parallels and text separate or wait for a database or what would you like to do there?

**Comment by sebastian-nehrdich** [comment]
Just imagine: Everytime I change a small thing about how we calculate the
quotes I need to re-run the matches which means to punch 40gb of vectors
through nearest neighbor search which takes about 5 hours on 40 cores from
start to finish for the Tibetan canon. In the end I end up with some 100gb+
of raw data which we need to merge in order to remove duplicates and after
that we might be left with some 8-10gb of json files.

Regarding the split of the data, I think we don't need to do that for now.
Let's see how things go and how soon we get Hubert under contract. if we in
middle of August still encounter problem with performance and the database
should be not done by that time, we can think again about changing this.
It's not a big operation and can be done in a few hours I think, if the
need should be there!

**Comment by ayya-vimala** [comment]
I can well imagine that that process is very tiring!
But I think the jsons that you generated with the offset values are just fine so if you want to make a full set of that and then change that over to the suttas-directory I'm happy with that.
If you want to do that in a flat directory structure, fine too. I will work with it and change the highlighting over tomorrow in any way you want to do it.

**Comment by sebastian-nehrdich** [comment]
I think by now I more or less got it right. We still have the problem that the marking of the offset is not extremely precise all the time - it can be off by two or three words. These is because the algorithm has some kind of built-in tolerance to allow variations and different words to occur, but this of course creates problems when it comes to the detection of precise boundaries. Maybe if we use this for a while I get some idea for a way to solve this, but at the moment we should not be too concerned and just try to use it as it is.

**Comment by ayya-vimala** [comment]
Okay, I had a look. It seems that the main change is in the json files itself and not the JS code (apart from directing the JS to look in the right place for the right file).
I'm just a bit confused that there are 2 separate directories but it seems that for the purposes of the highlighting, you use `suttas_new/tib` and the files in the directory `tibetan` are not used? Do I have that correct?
Those files in `suttas_new/tib` have a lot of `unsandied` stuff in there which you mentioned above to just ignore. So I will continue with those files only and merge it today.

**Comment by sebastian-nehrdich** [comment]
yes please ignore the tibetan-folder. I actually intended to delete that
but maybe I just overlooked it.
If you are OK with it I will remove the content of the suttas-folder and
replace it with the new JSONS tonight. This will probably break the website
itself but that's OK imho because we need to carry on anyways and the older
files have too many problems.

**Comment by ayya-vimala** [comment]
Sure, no problem. Once you have it replaced and I will make sure it corresponds with the loading and get that sorted.

**Comment by ayya-vimala** [comment]
When creating the json files, one thing you might want to keep in mind is that there are sometimes double spaces so you need to delete those. For instance, first parallel in TD4021E: 
`"mtshan  nyid sgrib pa de kho na //",` has 2 spaces between `mtshan` and `nyid` and that gets counted in the offset.

**Comment by sebastian-nehrdich** [comment]
Thank you for pointing that out! I wonder where these come from, another
thing to debug I suppose... :)

**Comment by ayya-vimala** [comment]
In the next one there are actually 4 spaces between `po` and `bsgom` and 2 between `dang` and `gnas` so it is a recurrent problem and not a one-off:
`"yang na gnyen po    bsgom pa dang  gnas`

**Comment by sebastian-nehrdich** [comment]
I found the bug that introduced the whitespace-problem and current files shouldn't have this anymore. I think we can close this soon. The offset of the Chinese files are a bit of sometimes but this we can discuss in the issue regarding the Chinese files.
