### ISSUE TITLE
Create highlighting for files with offset properties

### ISSUE THREAD

**Issue by ayya-vimala** [ayya-vimala/pali-networks#63]
On the left side text view, the highlighting will stay the same but within the parallels the matching text will be highlighted as well as on the right side.

**Comment by sebastian-nehrdich** [comment]
My thoughts on this are as follows:
- highlighting on the left side could stay the way it is right now because of the problem of overlapping quotes (as we discussed yesterday). I therefore agree that it kind of makes sense to highlight the entire segment on the left side.
- in the middle column where the list of parallels is presented, the part of the parallel that is the actual parallel should be highlighted. So at this point, we should make use of the par_set_offset_beg/end-values
- same goes for the display in the right side/third column: After clicking on a parallel in the middle, only the section that belongs to the parallel should be highlighted
- In my oppinion: On the left side, after clicking on a parallel in the middle, we should  highlight the part that belongs to the parallel by making use of the root_offset_beg/end-values. At the moment we use blue to indicate whether a segment has a parallel or not. After clicking on it, background color changes to yellow, which I think looks very nice. Now in my oppinion, it would be nice if this yellow highlighting will be controlled by the root_offset values, e.g. it will change according to the selected parallel, while the blue highlighting of the entire segment remains the same. I can imagine that this would be very nice to realize with a mouse-over-effect. What do you think?

**Comment by ayya-vimala** [comment]
I will have a look at this tomorrow. Sounds not so difficult but you never know .... :-)

**Comment by ayya-vimala** [comment]
I have made a separate branch for this so you can see this work. The files it uses are also there (in that branch) in suttas_new but I only added 3 of them in the Tibetan section to get it to work. (so best is T06T4021E, which I changed to have all available possibilities together in the first segment that has parallels so you can see it). I'm not entirely happy with it and the code needs to be cleaned up a bit but I'm running out of time and have already been working on this the entire day.
I've also not tested in on all variations in sanskrit etc yet but as long as you make the files consistent with the below changes I made to the json it should work fine too.

I have made some slight changes to the json files to make the notation consistent with the old files so as not to break anything that has nothing to do with the highlighting.

First of all, I changed `parseg` to `parsegment`.

Then the parsegnr don't match the segmentnr so I changed it back to the old system with just the number for the segmentnr. Maybe it would indeed be better to have the full number incl. filename but then we have to be consistent and use it with a `:` everywhere and not with a `_` in some places. But for now, I just wanted to make sure the files could be read by the frontend as it is.

**Comment by ayya-vimala** [comment]
I can merge this if you are happy with it and make all the json files like that.

**Comment by sebastian-nehrdich** [comment]
Thank you for this! I am preparing for class now and have no time to check
out the branch, but just a few remarks:
- The change of parseg to parsegment is fine with me
- I also noticed the problem with the segmentnr ('_' instead of ':'
sometimes) and this will be gone in the next generation of files
- I think we should stick to the full segmentnrs in order to avoid any kind
of possible confusion  (they are globally unique so there is less danger of
mixing up different element as compared to just using the numbers)
- the new files will also have the lang-tag
- I was thinking to change the naming of the folders in suttas/ so they are
identical to the nametags (e.g. 'san', 'pli' etc.). This makes it easier
for us to construct the paths for querying the parallel-files in the
frontend and makes things generally more consistent, what do you think?

**Comment by sebastian-nehrdich** [comment]
I had a look at it today and since the conference is now over I think we can merge this. The main problems currently are on the side of the files that I generated for testing, I am now working on fixing these. 
What I noticed:
- currently, sometimes a letter gets lost in the partially highlighted sections of the middle column (in TD4021, just the very first quotation T06TD4085E:153#27–155#15 you can see this happening)
- currently we highlight the entire segment on the left in blue. I thought about this for a while and I would prefer this highlighting to be starting from the lowest offset value of the quotes which are stored for that segment. Same should go for the end of the highlighting, e.g. it should end at the highest offset value. Now I remember what you said earlier about giving offset values for each single segment and this might really be a good strategy actually, because it helps with this problem! But let me think about this for a while.

**Comment by ayya-vimala** [comment]
Will have to see to the letters getting lost (I have an idea what the problem is and I can easily solve that). The highlighting does not yet work with the segment-view either.

If you can upload the sutta_new files (but to sutta instead) then it should work straight away (provided you make the changes to the JSON I said, otherwise it will break or I have to do some more work on it first)

**Comment by sebastian-nehrdich** [comment]
Now we have the problem of how to handle the case when we have various nested quotations stacked on top of each other. Orna suggested that we could try to use various shades of blue (e.g. light blue if there is only one quotation, darker when there are several quotations) to indicate such cases. I agree that this is a solution (maybe not the best, but it's something to start with). But I can imagine the implementation to a bit tricky (making the highlighing in accordance with the offset values and then checking how many layers are on top of each other, getting the right color values etc. - might be a bit of work! I will also have a look at the code and think about how we can solve this).

**Comment by ayya-vimala** [comment]
I've uploaded the code to GitHub. The problem with the scroll is solved. The segmentnumbers had changed to include the filename and that was the problem.
The files are not in a flat structure now but that is something that is easy to change if that is what it will be. I will await your files upload.
I will now start to work on making the highlighting work in the segment-table view as well.
I am not entirely sure what you mean with nested quotations. Can you give an example from the jsons?
I don't think shades of blue will work very well. Orna already had difficulty seeing the difference between grey and black on the screen.
We also have to consider which things are most important to do first. There are still quite a few things to do in cleaning up the code to make it more accessible when the database is installed. You won't see any changes when you look at the site but it will be quite a lot of work that will save a lot of hassle later.

**Comment by ayya-vimala** [comment]
PS. If the code is a letter off, best first to check in the json files for double spaces and make sure the offset is right.

**Comment by sebastian-nehrdich** [comment]
I agree that the layered quotations are not such a big issue at the moment and that different shades of color might also not be a perfect solution! 
I fixed the error with the spaces. That was something that was already present in the source files, for whatever reason. 
I prefer the flat structure because I can run my postprocessing scripts without recursion then, I have to twist my mind less! If that is ok with you. Especially because it seems that I have to debug this part at least five to ten times a day recently.  
The full upload of the Tibetan has to wait for another day, I just discovered a nasty bug during uploading the files and I have to redo it tomorrow. Currently the old Tibetan files are removed from the servers but the new, with the exception for one file, are not yet there (in suttas/tib/). 
Good news is that the first try on Chinese worked rather well. Also thanks to the hard work of the CBETA people we already have good catalogs and everything is pretty regularized. I might already upload the first file-list for the menus tomorrow, the first set of JSONS will follow very soon!

**Comment by ayya-vimala** [comment]
Sure. No hurry. I'm happy to do the flat structure if that's easier for you.
I found a nasty bug in the frontend that somehow seems to change the inputdata ... will take me a while to figure out too.

**Comment by sebastian-nehrdich** [comment]
ok, new data is online now! We seem to have a more serious problem with highly (self) referential files now. The quotations just get bloated up endlessly. This is why we now have some huge JSONS in the Prajñaparāmitā-section, while the other JSONS (like T06 etc.) are fine. I have to think a bit longer how to deal with these self-referential quotations in the PPS-files, I have no good idea yet what to do.

**Comment by ayya-vimala** [comment]
Is it not just possible to tell the system that when it finds a parallel with the same filename it should ignore it?
I saw the files and I noticed you made the tibetan in the directory 'tib' and the sanskrit still needs to be done.
Just one question: `unsandhied` is still in there. Should that be there?
Also, does the parlength need to be used for anything specific in the frontend? 

I can see the value of the root_offset and that those are values you might not want to loose, but it is not used in the frontend at present and then the jsons become bigger again ... I guess this will always be a problem until we have the database and then it does not matter how much info you add to it.

**Comment by sebastian-nehrdich** [comment]
it will certainly help to remove quotes from the same text, but I assume
that this alone will not solve the problem. I will discuss it with Orna.
The PPS-texts are self-referential and referential with each other, so this
combination creates the problems.
Regarding the root_offset: Imho, we should strive towards using these
values already now. ideally, we should not mark the entire segment blue,
but look for the lowest active root-offset value of the current parallels
and mark from this position onwards. In this way, the coloring on the left
side (first column) becomes more precise.
Yes parlength is important. We want to implement another filter based on
segment length. It has become very relevant with the new files.

**Comment by ayya-vimala** [comment]
I found something strange while testing with the new data.
For instance in T06T4021E.json, first segment there is a parallel:

```
            {
                "probability": 100,
                "parlength": 6,
                "parlang": "tib",
                "par_offset_beg": 26,
                "par_offset_end": 87,
                "parsegnr": [
                    "T04TD3924E:742"
                ],
                "parsegment": [
                    "de la nyes pa lnga ni dbus dang mtha' rnam par 'byed pa'i tshig le'ur byas pa las /"
                ],
```
The end-offset is 87 but the line is only 84 characters long.

**Comment by ayya-vimala** [comment]
How do you want to describe the filter for 'parlength'. It is easy to implement a filter for this but I don't know what to call it as I'm not sure what it does.

**Comment by sebastian-nehrdich** [comment]
Regarding the overflow of the length: Yes I can imagine how that happened,
will fix it! Thank you for finding it.
The length-filter is just that, e.g. a filter based on length of the quoted
passage given in words. Default value should be 4, max. value, I don't
know, let's try 30 and see how it goes? Maybe we can do that with the same
element that we now use for the probability filter...

**Comment by ayya-vimala** [comment]
I've been trying to get the root highlighting but it's extremely complicated to do because the root start and end offsets don't necessarily refer to the current segment. If that can be changed it will be easier.
So if you have 
```
    {
        "segmentnr": "T06TD4021E:2",
        "segment": "rgya gar skad du /",
        "lang": "tib",
        "parallels": [
            {
                ...
                "root_offset_beg": 0,
                "root_offset_end": -1,
                "root_segnr": [
                    "T06TD4021E:2"
                ]
            },
            {
                ...
                "root_offset_beg": 16,
                "root_offset_end": -1,
                "root_segnr": [
                    "T06TD4021E:1",
                    "T06TD4021E:2"
                ]
```
Would it be possible to have a segment-offset per segment? So in this case
```

    {
        "segmentnr": "T06TD4021E:2",
        "segment": "rgya gar skad du /",
        "seg_offset_beg": 0,
        "seg_offset_end": -1,
        "lang": "tib",
        "parallels": [
            {
                ...
                "root_offset_beg": 0,
                "root_offset_end": -1,
                "root_segnr": [
                    "T06TD4021E:2"
                ]
            },
            {
                ...
                "root_offset_beg": 16,
                "root_offset_end": -1,
                "root_segnr": [
                    "T06TD4021E:1",
                    "T06TD4021E:2"
                ]
```
To be honest, I have no idea how to get it done when I have to iterate going back and forth to previous or next segments. Unless you make an incredibly complicated function and that will take time to calculate. So for now I will abandon this and maybe get back to it at a later stage. 

(for the above example it does not matter that much because it will always find 0 and -1 as the values to take but in other cases it matters greatly, esp. if you get a 0 that refers to the start of the previous segment or a high end-value that refers to a later segment).

**Comment by sebastian-nehrdich** [comment]
One thing that is difficult with your proposed solution is that when one
changes any of the filters, the offsets don't get updated accordingly. So I
am afraid there is no easy way to avoid checking the offset values for each
parallel.
What I can do to make this less complicated is: for each parallel provide a
list of root_offset value pairs which has the same length as the list with
the root_segnr.
So if we have root_segnr = [ TD4064:1, TD4064:2, TD4064:3 ] I could provide
root_offsets = [ [12,-1],[0,-1],[0,12]] with each pair marking the start
and end of the highlight for the respective segment. Would that help you?
Just generally:
root_offset_beg of a quote refers to the current segment if the first
segment in root_segnr of that parallel is identical with the current
segment.
In the same way, root_offset_end refers to the current segment if the last
segment in root_segnr of that parallel is identical with the current
segment.
In all other cases, we should regard root_offset_beg as 0 and
root_offset_end as -1.

**Comment by ayya-vimala** [comment]
Basically the iteration is per segment and checking back and forth, calculating where in the previous segment the highlighting should have started while the iteration is already further is not so easy.
This might be a whole lot easier to do with a database than with a full file, but I'm not entirely sure.
The only thing I can do is say I'm at segment 2 and the list has segment 1 in it, to assume that THIS segment has to start at 0 but I cannot do anything any more about the previous segment 1. 

I uploaded the new highlighting version so Sanskrit is now broken.

But please have a very good look at the highlighting and let me know if I have read the offset properties correctly. For some it looks okay to me but for others not ... but I might be wrong. Is it 1 off somewhere? And give me a concrete example so I can check with that. Thanks!

**Comment by sebastian-nehrdich** [comment]
in my eyes, you can simplify the algorithm because look ahead / look behind is not cessary. I would just calculate for highlighting for the current segment and check for the following cases:
1. no parallel - good, no highlighting
2. has parallel - then we need to do three things:
 2.1 check if if the current segment is a middle-segment, that means neither beginning or end, in any of the parallels - if so, mark the entire thing blue.
 2.2 if it's never a middle segment, then check if it is a beginning segment in any case - if so, get the lowester value for  root_offset_beg and highlight from there on
 2.3 check if it's a last-segment in any case and if so, get the highest value root_offset_end value and stop highlighting there


The current highlighting looks technically good to me! I will check closer tomorrow but I assume that some more debugging has to be done regarding the jsons themselves.

**Comment by ayya-vimala** [comment]
Hold on .. I think we are talking cross purposes here.
There are 2 types of highlighting: 
1. in the parallels boxes in both the text view and the segment table view as well as in the right column in the text view (parallel segments).
2. highlighting in the first left-column (root segments).

I have only done the highlighting for 1 - parallel segments. Just want to know it that is okay or 1 off. 
The highlighting in 2 I will have a look tomorrow.

**Comment by sebastian-nehrdich** [comment]
Everything in my comment with the exception of the last sentence was about
2. highlighting in the first left-column (root segments)!
The last comment was about the current state of the highlighting of the
parallels boxes as it is on the website right now.
Hope that makes it more clear!

**Comment by sebastian-nehrdich** [comment]
a small note: Currently, if the highlighting starts in the middle of a word (which shouldn't happen in Tibetan but I guess it's a fault in my data, not a big deal), we get a space inserted where the highlighting starts/ends, that is not ideal. Apart from that it looks fine to me!

**Comment by sebastian-nehrdich** [comment]
A new day, a new set of files. I rewrote the algorithm to create the offset-values this morning and it looks much better now. It is still not perfect (especially Kārikas such as an TD4021 don't look nice), but prose-quotations like in TD4064 generally look quite good!

**Comment by ayya-vimala** [comment]
Great. Good work.
I am away this morning but was thinking about changing the highlighting code a bit because it is just a mess right now. 
Can you confirm one thing to me: is double-danda `||` (after which a linebreak should appear) only to be found at the END of segments or can it also appear in the middle of a segment? If it is only at the end of the segment the code can be much simplified.

**Comment by sebastian-nehrdich** [comment]
With Tibetan, yes. With Sanskrit in the current situation, unfortunately
no...
But if it helps you: We can disregard linebreaks after double-danda if
double-danda occurs not at the end of the segment. I am now mainly thinking
about ill-formatted GRETIL files, and in that case it will not matter much
anyway. So we can do it that way if it is easier for you.

**Comment by ayya-vimala** [comment]
Gretil will be updated to a better format soon anyway so I think we can safely discard that for now until they are done. Because what I do right now is kit all the segments together to a string and then split them again where the double-danda is but that is hacky and a bit tricky with the highlighting end-values. Best to keep the array as it is with the segments as they are; much cleaner way of working.

**Comment by sebastian-nehrdich** [comment]
I agree! Don't put too much work into the current GRETIL files, these
problems will disappear in the future anyway.

**Comment by ayya-vimala** [comment]
Got it working but now other things have broken so got to work on it a bit more.

**Comment by sebastian-nehrdich** [comment]
cool! By the way I have pushed the new version of the website with the
changed menus to our server. This is because I need Orna's feedback on
this. So maybe for the next 12-24h, please don't overwrite this (or if you
do, merge it before with the menus-new-branch so the new menus don't
disappear).
This version is in the menus-new branch here on github. I also have some
Chinese files working now, I will comment on it in the other issue.

**Comment by ayya-vimala** [comment]
Sorry, what new menus? I don't think we discussed this. Is there an issue for it? What has changed?

**Comment by sebastian-nehrdich** [comment]
https://github.com/ayya-vimala/pali-networks/issues/71

The code is in the menus-new branch!

**Comment by ayya-vimala** [comment]
I have updated the highlighting and that should all be working now.
What if you upload your branch code to a different branch (with just a few sutta files to match and show what it does)? It might be easier if we have a master-branch and a second "staging" site running at the same time. We did this with SC all the time too.

**Comment by ayya-vimala** [comment]
I found another bug but fixed the bug with the extra spaces. That was something that has apparently changed in lit html but that is working now. Hope to upload new version later today.

**Comment by ayya-vimala** [comment]
Okay, that works now.
I think the "layering" is not needed really because you can work with the filters. You can say for instance to only show the parallels for file X and then it will also only show the highlighting for the parallels in that specific file. When you learn to work with the filtering you can get all the data out.

This hightlighting has to be still tested for the Sanskrit because that might be broken in a few places but will make a new issue for that once you have uploaded the Sanskrit files.

**Comment by sebastian-nehrdich** [comment]
Yes for Tibetan (and appearantly Chinese as well, didn't check carefully though), it is working wonderful, great job! Sanskrit I will upload in a few days, then we can see how that will be.

**Comment by ayya-vimala** [comment]
Back to In Progress ... still more bugs!

**Comment by sebastian-nehrdich** [comment]
From my observation, I don't see any major bugs left anymore.
