### ISSUE TITLE
Flatten the folder structure

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#66]
Currently our structure for the sutta/-folder is:
sanskrit/
tibetan/
(pali, chinese etc.)
and then we have the subfolders:
T01/
T02/
(etc.)
Now I am wondering: We also include the category-names in the files themselves (T06TD4064E etc.). Do we need the subfolders for the categories? It seems to be a bit redundant to me. It could save me a step during data generation if I don't have to care about the subfolders and also it could simplify the scripts that I use for postprocessing becaue no recursive operations are needed with a flat folder structure.
So I would prefer to just have
sanskrit/
tibetan/
And that's it. Or do you have a reason why it is better to have further subfolders?

**Comment by ayya-vimala** [comment]
In SuttaCentral we have far more subfolders in order prevent having huge folders where it becomes difficult to find anything. I changed the folders to subfolders to make it a bit more workable. I do realize it is easier to find something without subfolders but it is not a really big deal because it is easy to find when we have the category name in the filename.
