### ISSUE TITLE
Display of Chinese in text-view

### ISSUE THREAD

**Issue by sebastian-nehrdich** [ayya-vimala/pali-networks#75]
I have uploaded the first set of Chinese JSONS to the server. Menus are also there, the code in the menu-new branch should be able to display the menus and the new files. 
The display already works nicely in my opinion. A few things on the cosmetic level remain that we should look into: 
1. print a newline at the end of each segment
2. Have some kind of paragraph (double newline or similar) before each segment where the segmentnr ends in _0. 
3. Opening of the parallel file in the third column after clicking on a parallel does not yet work.

**Comment by ayya-vimala** [comment]
Installing some other font might be needed too. Not all regular fonts have the full chinese dataset so best to check. This is especially an issue with Buddhist chinese because font generally only have modern chinese so some characters might render wrong using the wrong fontset. We've had that issue in SC too and it took a while to get right. Also, the Taisho online version is a modified version because not all fonts were available. Unfortunately there is nothing we can do about that: up to them!

**Comment by sebastian-nehrdich** [comment]
This is good to know! I might ask Kiyonori if he can help us out with a
good font.

**Comment by ayya-vimala** [comment]
SC uses Noto Sans CJK TC which is freely available.

**Comment by sebastian-nehrdich** [comment]
Regarding the line breaks, It looks great the way it is right now, Nothing to change in my opinion!

**Comment by sebastian-nehrdich** [comment]
@ayya-vimala I have to ask you to do a small hack on the frontend: 
We should insert a line break/paragraph break before segments that contain three or more consecutive spaces. This means that they are (very very likely) a verse. 
For example if you open T31T1585, there is relatively early in the file the following line: 
１ 由假說我法 有種種相轉 彼依識所變 此能變唯三 
In the current git-version of the site this is rendered as a seperate parapgraph which is already good. 
Better it would be if there is another line-break between 有種種相轉  and 彼依識所變.
So the ideal display would be: 
１ 由假說我法 有種種相轉 
     彼依識所變 此能變唯三
Somehow of course it would be great if the first two padas and the next two padas of the verse appear aligned so that they match perfectly (I hope you can understand what I mean). 
 
I can fix this during data-generation but the problem is that I have already generated the data and because of the insane amount of Chinese data, regenerating data takes roughly 24 hours and I have to use my CPUs for other things at the moment...  Of course later generations of files will not have this problem anymore.
Apart from this, the display is fine in my eyes. You can disregard all my earlier comments regarding line-breaks,

**Comment by ayya-vimala** [comment]
Ha ... whenever you say "small" it turns out not to be that easy. I messed around with it for a while but without any satisfactory results. I will leave it for now until an idea comes up.
This will require quite a bit of work, also because the code is not always consistent. There is for instance also 3 spaces behind the number, and in between the first two groups so you would get 5 lines in total instead of 2. And then aligning them in this setup would also be difficult.
Then there is the problem that these are not strings but html objects so I have to split the lines into a list first and then put them together as an html object but that also messes again with the highlighting ...

**Comment by ayya-vimala** [comment]
Okay .. got it!
Just aligning it will be difficult. Before every verse there is either a number or two and sometimes a start quotemark. So I would have to analyse each line to see what offset needs to be taken for the next line(s), which is different for each one.

**Comment by sebastian-nehrdich** [comment]
thank you very much! I think it looks great the way it is now.
Actually never mind about aligning pada a and b with c and d! I think that
is pretty much impossible (or at least a very very tough job) without
properly marked up xml data.
I also don't think that this would be really necessary. The way the Chinese
is displayed now is very, very good! I like the 'middle alignment' solution
that you choose for the Kārikas, looks very neat.
